In [1]:
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)

In [2]:
f_data = np.loadtxt('test.csv', delimiter=',', dtype=np.float32)
f_test = np.loadtxt('test2.csv', delimiter=',', dtype=np.float32)

# m_data = f_data[:, 0:1]
# n_data = f_data[:, 1:2]
# r_data = f_data[:, 2:3]
# f_result = f_data[:, 3:4]
# f_test1 = f_test[:]
learning_rate = 0.001
training_epochs = 10000
batch_size = 100
display_step = 50

x_data = f_data[:, 0:-1]
y_data = f_data[:, [-1]]

x_test = f_test[:, 0:-1]
y_test = f_test[:, [-1]]

In [3]:
# print(m_data.shape, m_data, len(m_data))
# print(n_data.shape, n_data, len(n_data))
# print(r_data.shape, r_data, len(r_data))
# print(f_result.shape, f_result, len(f_result))
# print(f_test1.shape, f_test1, len(f_test1))

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data, len(y_data))

print(x_test.shape, x_test, len(x_test))
print(y_test.shape, y_test, len(y_test))

(1000000, 3) [[ 0.081       0.829       0.81699997]
 [ 0.96799999  0.89899999  0.162     ]
 [ 0.64700001  0.44600001  0.89399999]
 ..., 
 [ 0.31200001  0.773       0.53100002]
 [ 0.926       0.294       0.199     ]
 [ 0.74299997  0.152       0.51899999]] 1000000
(1000000, 1) [[  0.10059941]
 [ 33.15927505]
 [  0.3610473 ]
 ..., 
 [  0.85500002]
 [  6.875     ]
 [  0.419     ]] 1000000
(20000, 3) [[ 0.47142059  0.316365    0.55487716]
 [ 0.23590474  0.28930765  0.0159295 ]
 [ 0.44853005  0.50930876  0.14194755]
 ..., 
 [ 0.39976066  0.42009386  0.29273492]
 [ 0.4884086   0.41115412  0.78293502]
 [ 0.77018207  0.16797483  0.9245882 ]] 20000
(20000, 1) [[  4.84399021e-01]
 [  2.68962860e+02]
 [  1.13374872e+01]
 ..., 
 [  1.95973492e+00]
 [  3.27594429e-01]
 [  1.51335523e-01]] 20000


In [4]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W1 = tf.Variable(tf.random_normal([3,8]), name='weight1')
b1 = tf.Variable(tf.random_normal([8]), name='bias1')
layer1 = tf.matmul(X, W1) + b1

# layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([8,8]), name='weight2')
b2 = tf.Variable(tf.random_normal([8]), name='bias2')
layer2 = tf.matmul(layer1, W2) + b2

W3 = tf.Variable(tf.random_normal([8,6]), name='weight2')
b3 = tf.Variable(tf.random_normal([6]), name='bias2')
layer3 = tf.matmul(layer2, W3) + b3

W4 = tf.Variable(tf.random_normal([6,6]), name='weight2')
b4 = tf.Variable(tf.random_normal([6]), name='bias2')
layer4 = tf.matmul(layer3, W4) + b4

W5 = tf.Variable(tf.random_normal([6,1]), name='weight2')
b5 = tf.Variable(tf.random_normal([1]), name='bias2')
hypothesis = tf.matmul(layer4, W5) + b5

# W2 = tf.Variable(tf.random_normal([3, 3]), name='weight2')
# b2 = tf.Variable(tf.random_normal([3]), name='bias2')
# layer2 = tf.nn.relu(tf.matmul(layer1, W2) + b2)

# W3 = tf.Variable(tf.random_normal([3, 3]), name='weight3')
# b3 = tf.Variable(tf.random_normal([1]), name='bias3')
# hypothesis = tf.nn.relu(tf.matmul(layer2, W3) + b3)

In [5]:
# cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [6]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

feed_dict = {X: x_data, Y: y_data}
for epoch in range(training_epochs):
    sess.run(optimizer, feed_dict)

        # Display logs per epoch step
    if (epoch+1) % display_step == 0:
        current_loss = sess.run(cost, feed_dict)
        print("Epoch:", '%04d' % (epoch+1), "cost=", "{:.9f}".format(current_loss),
            "W=", sess.run(W3), "b=", sess.run(b3))

print("Optimization Finished!")
training_cost = sess.run(cost, feed_dict={X: x_data, Y: y_data})
print("Training cost=", training_cost, "W=", sess.run(W), "b=", sess.run(b), '\n')


# for step in range(1001):
#     cost_val, hy_val, _ = sess.run(
#         [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
#     if step % 10 == 0:
#         print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

# # Ask my score
# print("Your score will be ", sess.run(
#     hypothesis, feed_dict={X: x_test}))

Epoch: 0050 cost= nan W= [[ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]] b= [ nan  nan  nan  nan  nan  nan]
Epoch: 0100 cost= nan W= [[ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]] b= [ nan  nan  nan  nan  nan  nan]
Epoch: 0150 cost= nan W= [[ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]] b= [ nan  nan  nan  nan  nan  nan]


KeyboardInterrupt: 

In [ ]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

f_data = np.loadtxt('test.csv', delimiter=',', dtype=np.float32)
f_test = np.loadtxt('test2.csv', delimiter=',', dtype=np.float32)

def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [ ]:
# very important. It does not work without it.
f_data = MinMaxScaler(f_data)
f_test = MinMaxScaler(f_test)
print(f_data)
print(f_test)

In [ ]:
x_data = f_data[:, 0:-1]
y_data = f_data[:, [-1]]

x_test = f_test[:, 0:-1]
y_test = f_test[:, [-1]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W1 = tf.Variable(tf.random_normal([3,4]), name='weight1')
b1 = tf.Variable(tf.random_normal([4]), name='bias1')
layer1 = tf.matmul(X, W1) + b1

# layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([4,4]), name='weight2')
b2 = tf.Variable(tf.random_normal([4]), name='bias2')
layer2 = tf.matmul(layer1, W2) + b2

W3 = tf.Variable(tf.random_normal([4,1]), name='weight2')
b3 = tf.Variable(tf.random_normal([1]), name='bias2')
hypothesis = tf.matmul(layer2, W3) + b3

# W2 = tf.Variable(tf.random_normal([3, 3]), name='weight2')
# b2 = tf.Variable(tf.random_normal([3]), name='bias2')
# layer2 = tf.nn.relu(tf.matmul(layer1, W2) + b2)

# W3 = tf.Variable(tf.random_normal([3, 3]), name='weight3')
# b3 = tf.Variable(tf.random_normal([1]), name='bias3')
# hypothesis = tf.nn.relu(tf.matmul(layer2, W3) + b3)

# placeholders for a tensor that will be always fed.

# Hypothesis

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-4)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(1001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
    
print("Learning finished")

In [ ]:
print("Accuracy: ", accuracy.eval(session=sess, feed_dict={X: x_test, Y: y_test}))