In [42]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
tf.set_random_seed(777)  # for reproducibility

#f_data = np.loadtxt('crack_or_cicle_training4.csv', delimiter=',', dtype=np.float32)
#f_test = np.loadtxt('crack_or_cicle_test.csv', delimiter=',', dtype=np.float32)

case1_circle = np.loadtxt('circle_only_traing.csv', delimiter=',', dtype=np.float32)
case1_circle_test = np.loadtxt('circle_only_test.csv', delimiter=',', dtype=np.float32)
case1_circle_traingtest = np.loadtxt('circle_only_traingtest.csv', delimiter=',', dtype=np.float32)

case2_crack = np.loadtxt('crack_only_traing.csv', delimiter=',', dtype=np.float32)
case2_crack_test = np.loadtxt('crack_only_test.csv', delimiter=',', dtype=np.float32)
case2_crack_traingtest = np.loadtxt('crack_only_traingtest.csv', delimiter=',', dtype=np.float32)

case3_training = np.loadtxt('crack_or_cicle_trainingset.csv', delimiter=',', dtype=np.float32)
case3_test_cicle = np.loadtxt('crack_or_cicle_circle.csv', delimiter=',', dtype=np.float32)
case3_test_crack = np.loadtxt('crack_or_cicle_crack.csv', delimiter=',', dtype=np.float32)
case3_test_elipse = np.loadtxt('crack_or_cicle_elipse.csv', delimiter=',', dtype=np.float32)

f_test = np.loadtxt('crack_or_cicle_test.csv', delimiter=',', dtype=np.float32)


def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [29]:
case1_circle = MinMaxScaler(case1_circle)
case1_circle_test = MinMaxScaler(case1_circle_test)
case1_circle_traingtest = MinMaxScaler(case1_circle_traingtest)

case2_crack = MinMaxScaler(case2_crack)
case2_crack_test = MinMaxScaler(case2_crack_test)
case2_crack_traingtest = MinMaxScaler(case2_crack_traingtest)

case3_training = MinMaxScaler(case3_training)
case3_test_cicle = MinMaxScaler(case3_test_cicle)
case3_test_crack = MinMaxScaler(case3_test_crack)
case3_test_elipse = MinMaxScaler(case3_test_elipse)


In [43]:
x_data_case1 = case1_circle[:, 0:-1]
y_data_case1 = case1_circle[:, [-1]]

#x_test_case1 = case1_circle_traingtest[:, 0:-1]
#y_test_case1 = case1_circle_traingtest[:, [-1]]
x_test_case1 = x_data_case1[0:100, ]
y_test_case1 = y_data_case1[0:100, ]
x_test2_case1 = case1_circle_test[:, 0:-1]
y_test2_case1 = case1_circle_test[:, [-1]]

##############
x_data_case2 = case2_crack[:, 0:-1]
y_data_case2 =case2_crack[:, [-1]]

#x_test_case2 = case2_crack_traingtest[:, 0:-1]
#y_test_case2 = case2_crack_traingtest[:, [-1]]
x_test_case2 = x_data_case2[0:100, ]
y_test_case2 = y_data_case2[0:100, ]

x_test2_case2 = case2_crack_test[:, 0:-1]
y_test2_case2 = case2_crack_test[:, [-1]]
##############
x_data_case3 = case3_training[:, 0:-1]
y_data_case3 = case3_training[:, [-1]]

x_test_case3 = case3_test_cicle[:, 0:-1]
y_test_case3 = case3_test_cicle[:, [-1]]
x_test2_case3 = case3_test_crack[:, 0:-1]
y_test2_case3 = case3_test_crack[:, [-1]]
x_test3_case3 = case3_test_elipse[:, 0:-1]
y_test3_case3 = case3_test_elipse[:, [-1]]
##############
#y_test = f_test[:, [-1]]



In [44]:
print("---x_data_case1-case---")
print(x_data_case1[0:10, :])
print("---x_test_case1---")
print(x_test_case1[0:10, :])

---x_data_case1-case---
[[ 0.12800001  0.12800001]
 [ 0.56999999  0.56999999]
 [ 0.78299999  0.78299999]
 [ 0.93599999  0.93599999]
 [ 0.493       0.493     ]
 [ 0.75        0.75      ]
 [ 0.912       0.912     ]
 [ 0.40700001  0.40700001]
 [ 0.85000002  0.85000002]
 [ 0.57200003  0.57200003]]
---x_test_case1---
[[ 0.12800001  0.12800001]
 [ 0.56999999  0.56999999]
 [ 0.78299999  0.78299999]
 [ 0.93599999  0.93599999]
 [ 0.493       0.493     ]
 [ 0.75        0.75      ]
 [ 0.912       0.912     ]
 [ 0.40700001  0.40700001]
 [ 0.85000002  0.85000002]
 [ 0.57200003  0.57200003]]


In [45]:
print("---y_data_case1-case---")
print(y_data_case1[0:10, :])
print("---y_test_case1---")
print(y_test_case1[0:10, :])

---y_data_case1-case---
[[ 0.049152  ]
 [ 0.97469997]
 [ 1.83926702]
 [ 2.62828803]
 [ 0.72914702]
 [ 1.6875    ]
 [ 2.49523211]
 [ 0.49694699]
 [ 2.16750002]
 [ 0.981552  ]]
---y_test_case1---
[[ 0.049152  ]
 [ 0.97469997]
 [ 1.83926702]
 [ 2.62828803]
 [ 0.72914702]
 [ 1.6875    ]
 [ 2.49523211]
 [ 0.49694699]
 [ 2.16750002]
 [ 0.981552  ]]


In [46]:
X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W1 = tf.Variable(tf.random_normal([2,4]), name='weight1')
b1 = tf.Variable(tf.random_normal([4]), name='bias1')
layer1 = tf.nn.relu(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([4,4]), name='weight2')
b2 = tf.Variable(tf.random_normal([4]), name='bias2')
layer2 = tf.nn.relu(tf.matmul(layer1, W2) + b2)

W3 = tf.Variable(tf.random_normal([4,4]), name='weight3')
b3 = tf.Variable(tf.random_normal([4]), name='bias3')
layer3 = tf.nn.relu(tf.matmul(layer2, W3) + b3)

W4 = tf.Variable(tf.random_normal([4,1]), name='weight4')
b4 = tf.Variable(tf.random_normal([1]), name='bias4')
hypothesis = tf.matmul(layer3, W4) + b4



In [15]:
learning_rate = [0.001, 0.01]
training_step = [1000, 2000, 10000, 50000, 100000]

In [47]:
for learning in learning_rate:
    print(learning)
    
for training in training_step:
    print(training)


0.001
0.01
1000
2000
10000
50000
100000


In [83]:
x_test_case1 = x_data_case1[0:100, ]
y_test_case1 = y_data_case1[0:100, ]

x_dataset = [x_data_case1[0:10], x_data_case1[0:50], x_data_case1[0:100], x_data_case1[0:500], x_data_case1[0:1000]]
y_dataset = [y_data_case1[0:10], y_data_case1[0:50], y_data_case1[0:100], y_data_case1[0:500], y_data_case1[0:1000]]


x2_dataset = [x_data_case2[0:10], x_data_case2[0:50], x_data_case2[0:100], x_data_case2[0:500], x_data_case2[0:1000]]
y2_dataset = [y_data_case2[0:10], y_data_case2[0:50], y_data_case2[0:100], y_data_case2[0:500], y_data_case2[0:1000]]
#testset = 
# for i in x_dataset
#     print("------ x_length : ", len(i), " ---------")
#     print(i)
#####
# for i in range(len(x_dataset)):
#     print("------ x_length : ", len(x_dataset[i]), " ---------")
#     print(x_dataset[i])
#     print("------ y_length : ", len(y_dataset[i]), " ---------")
#     print(y_dataset[i])
#####
# for j in y_dataset:
#     print("------ y_length : ", len(j), " ---------")
#     print(j)
    


------ x_length :  10  ---------
[[ 0.12800001  0.12800001]
 [ 0.56999999  0.56999999]
 [ 0.78299999  0.78299999]
 [ 0.93599999  0.93599999]
 [ 0.493       0.493     ]
 [ 0.75        0.75      ]
 [ 0.912       0.912     ]
 [ 0.40700001  0.40700001]
 [ 0.85000002  0.85000002]
 [ 0.57200003  0.57200003]]
------ y_length :  10  ---------
[[ 0.049152  ]
 [ 0.97469997]
 [ 1.83926702]
 [ 2.62828803]
 [ 0.72914702]
 [ 1.6875    ]
 [ 2.49523211]
 [ 0.49694699]
 [ 2.16750002]
 [ 0.981552  ]]
------ x_length :  50  ---------
[[ 0.12800001  0.12800001]
 [ 0.56999999  0.56999999]
 [ 0.78299999  0.78299999]
 [ 0.93599999  0.93599999]
 [ 0.493       0.493     ]
 [ 0.75        0.75      ]
 [ 0.912       0.912     ]
 [ 0.40700001  0.40700001]
 [ 0.85000002  0.85000002]
 [ 0.57200003  0.57200003]
 [ 0.49200001  0.49200001]
 [ 0.26199999  0.26199999]
 [ 0.58099997  0.58099997]
 [ 0.79799998  0.79799998]
 [ 0.27000001  0.27000001]
 [ 0.90200001  0.90200001]
 [ 0.98400003  0.98400003]
 [ 0.114       0.114

In [85]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
cost_history = np.empty(shape=[1],dtype=float)

learning1 = 0.02
training1 = 100000
optimizer = tf.train.AdamOptimizer(learning_rate=learning1).minimize(cost)
correct_prediction = tf.equal(tf.argmax(hypothesis, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print("---------------------------")
print("--[Learning Rate = ", learning1,"]--")
print("--[  Iteration   = ", training1,"  ]--")
print("---------------------------")

for i in range(len(x_dataset)):
    print("--------x_dataset = ", len(x_dataset[i]),"----------")
    for epoch in range(training1+1):
                cost_val, hy_val, _ = sess.run([cost, hypothesis,optimizer],feed_dict={X:x_dataset[i],Y:y_dataset[i]})
               # cost_history = np.append(cost_history,sess.run(cost,feed_dict={X: x_data,Y: y_data}))
                if epoch % 1000 ==0:
                        print("Step: ", epoch, "Cost: ", cost_val)
                if training1 == epoch:
                    print("---------------------------")
                    print("Learning finished")
                    print("---------------------------")
                    print("case1_circle_traingtest start")
                    print("---------------------------")
                    test_val, test_hy = sess.run([cost,hypothesis], feed_dict={X:x_test_case1, Y: y_test_case1})
                    print("Test error", test_val, "\n" "Test Prediction" "\n", test_hy )
                    print("---------------------------")
                    print("case1_circle_test start")
                    print("---------------------------")
                    test_val, test_hy = sess.run([cost,hypothesis], feed_dict={X:x_test2_case1, Y: y_test2_case1})
                    print("Test error", test_val, "\n" "Test Prediction" "\n", test_hy )



---------------------------
--[Learning Rate =  0.02 ]--
--[  Iteration   =  100000   ]--
---------------------------
--------x_dataset =  10 ----------
Step:  0 Cost:  16.0482
Step:  1000 Cost:  0.0353945
Step:  2000 Cost:  0.0353945
Step:  3000 Cost:  0.0353945
Step:  4000 Cost:  0.0353945
Step:  5000 Cost:  0.0353945
Step:  6000 Cost:  0.00166936
Step:  7000 Cost:  0.00166887
Step:  8000 Cost:  0.00166884
Step:  9000 Cost:  0.00166885
Step:  10000 Cost:  0.0016757
Step:  11000 Cost:  0.00196754
Step:  12000 Cost:  0.00165344
Step:  13000 Cost:  0.000420882
Step:  14000 Cost:  5.47713e-05
Step:  15000 Cost:  4.98143e-05
Step:  16000 Cost:  4.78818e-05
Step:  17000 Cost:  0.00023399
Step:  18000 Cost:  5.18941e-05
Step:  19000 Cost:  0.000114
Step:  20000 Cost:  4.78385e-05
Step:  21000 Cost:  4.78997e-05
Step:  22000 Cost:  4.77337e-05
Step:  23000 Cost:  4.94204e-05
Step:  24000 Cost:  4.26892e-05
Step:  25000 Cost:  6.12443e-06
Step:  26000 Cost:  6.27828e-05
Step:  27000 Cost:  2.

Step:  49000 Cost:  7.84536e-05
Step:  50000 Cost:  2.87099e-05
Step:  51000 Cost:  1.54479e-05
Step:  52000 Cost:  5.37342e-05
Step:  53000 Cost:  4.65985e-05
Step:  54000 Cost:  1.20977e-05
Step:  55000 Cost:  1.20657e-05
Step:  56000 Cost:  5.30974e-05
Step:  57000 Cost:  1.89739e-05
Step:  58000 Cost:  0.000101341
Step:  59000 Cost:  1.24939e-05
Step:  60000 Cost:  4.32128e-05
Step:  61000 Cost:  4.25158e-05
Step:  62000 Cost:  1.46958e-05
Step:  63000 Cost:  0.000125589
Step:  64000 Cost:  3.62847e-05
Step:  65000 Cost:  2.31567e-05
Step:  66000 Cost:  3.51461e-05
Step:  67000 Cost:  8.55087e-05
Step:  68000 Cost:  2.6584e-05
Step:  69000 Cost:  2.80232e-05
Step:  70000 Cost:  3.52869e-05
Step:  71000 Cost:  7.40217e-05
Step:  72000 Cost:  4.38207e-05
Step:  73000 Cost:  8.09183e-05
Step:  74000 Cost:  0.000319018
Step:  75000 Cost:  4.00769e-05
Step:  76000 Cost:  2.7881e-05
Step:  77000 Cost:  4.50413e-05
Step:  78000 Cost:  7.14849e-05
Step:  79000 Cost:  7.54526e-06
Step:  800

Step:  1000 Cost:  1.91412e-05
Step:  2000 Cost:  3.57946e-05
Step:  3000 Cost:  1.4191e-05
Step:  4000 Cost:  1.32304e-05
Step:  5000 Cost:  1.23247e-05
Step:  6000 Cost:  1.19868e-05
Step:  7000 Cost:  1.27091e-05
Step:  8000 Cost:  5.78349e-05
Step:  9000 Cost:  1.3746e-05
Step:  10000 Cost:  1.17208e-05
Step:  11000 Cost:  5.33688e-05
Step:  12000 Cost:  1.10047e-05
Step:  13000 Cost:  2.56139e-05
Step:  14000 Cost:  1.09194e-05
Step:  15000 Cost:  1.04958e-05
Step:  16000 Cost:  1.06418e-05
Step:  17000 Cost:  1.44699e-05
Step:  18000 Cost:  9.98653e-05
Step:  19000 Cost:  1.04759e-05
Step:  20000 Cost:  1.03989e-05
Step:  21000 Cost:  0.000193611
Step:  22000 Cost:  1.66277e-05
Step:  23000 Cost:  1.03639e-05
Step:  24000 Cost:  1.02393e-05
Step:  25000 Cost:  1.02383e-05
Step:  26000 Cost:  1.01685e-05
Step:  27000 Cost:  1.02663e-05
Step:  28000 Cost:  1.42814e-05
Step:  29000 Cost:  0.000105849
Step:  30000 Cost:  1.01827e-05
Step:  31000 Cost:  1.22759e-05
Step:  32000 Cost: 

Step:  53000 Cost:  1.83306e-05
Step:  54000 Cost:  1.00748e-05
Step:  55000 Cost:  1.83267e-05
Step:  56000 Cost:  1.01398e-05
Step:  57000 Cost:  1.41976e-05
Step:  58000 Cost:  1.55004e-05
Step:  59000 Cost:  1.38524e-05
Step:  60000 Cost:  7.34284e-05
Step:  61000 Cost:  1.04472e-05
Step:  62000 Cost:  1.17637e-05
Step:  63000 Cost:  2.28659e-05
Step:  64000 Cost:  1.64495e-05
Step:  65000 Cost:  1.41345e-05
Step:  66000 Cost:  0.000222696
Step:  67000 Cost:  1.01126e-05
Step:  68000 Cost:  8.57887e-05
Step:  69000 Cost:  1.25075e-05
Step:  70000 Cost:  7.80182e-05
Step:  71000 Cost:  1.02833e-05
Step:  72000 Cost:  1.20259e-05
Step:  73000 Cost:  1.11818e-05
Step:  74000 Cost:  1.01789e-05
Step:  75000 Cost:  1.07865e-05
Step:  76000 Cost:  8.236e-05
Step:  77000 Cost:  1.29292e-05
Step:  78000 Cost:  1.57345e-05
Step:  79000 Cost:  2.98388e-05
Step:  80000 Cost:  1.00657e-05
Step:  81000 Cost:  1.11363e-05
Step:  82000 Cost:  1.18305e-05
Step:  83000 Cost:  0.000103191
Step:  840

In [ ]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
cost_history = np.empty(shape=[1],dtype=float)

learning1 = 0.01
training1 = 10000
optimizer = tf.train.AdamOptimizer(learning_rate=learning1).minimize(cost)
correct_prediction = tf.equal(tf.argmax(hypothesis, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print("---------------------------")
print("--[Learning Rate = ", learning1,"]--")
print("--[  Iteration   = ", training1,"  ]--")
print("---------------------------")

        for epoch in range(training1+1):
            cost_val, hy_val, _ = sess.run([cost, hypothesis,optimizer],feed_dict={X:x_data_case2, Y: y_data_case2})
           # cost_history = np.append(cost_history,sess.run(cost,feed_dict={X: x_data,Y: y_data}))
            if epoch % 1000 ==0:
                    print("Step: ", epoch, "Cost: ", cost_val)
           
            if training == epoch:
                print("---------------------------")
                print("Learning finished")
                print("---------------------------")
                print("case2_crack_traingtest start")
                print("---------------------------")
                test_val, test_hy = sess.run([cost,hypothesis], feed_dict={X:x_test_case2, Y: y_test_case2})
                print("Test error", test_val, "\n" "Test Prediction" "\n", test_hy )
                print("---------------------------")
                print("case2_crack_test start")
                print("---------------------------")
                test_val, test_hy = sess.run([cost,hypothesis], feed_dict={X:x_test2_case2, Y: y_test2_case2})
                print("Test error", test_val, "\n" "Test Prediction" "\n", test_hy )
             


In [ ]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
cost_history = np.empty(shape=[1],dtype=float)

learning1 = 0.01
training1 = 10000
optimizer = tf.train.AdamOptimizer(learning_rate=learning1).minimize(cost)
correct_prediction = tf.equal(tf.argmax(hypothesis, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print("---------------------------")
print("--[Learning Rate = ", learning1,"]--")
print("--[  Iteration   = ", training1,"  ]--")
print("---------------------------")

        for epoch in range(training1+1):
            cost_val, hy_val, _ = sess.run([cost, hypothesis,optimizer],feed_dict={X:x_data_case2, Y: y_data_case2})
           # cost_history = np.append(cost_history,sess.run(cost,feed_dict={X: x_data,Y: y_data}))
            if epoch % 1000 ==0:
                    print("Step: ", epoch, "Cost: ", cost_val)
                    
            if training == epoch:
                print("---------------------------")
                print("Learning finished")
                print("---------------------------")
                print("Case3_Circle_test start")
                print("---------------------------")
                test_val, test_hy = sess.run([cost,hypothesis], feed_dict={X:x_test_case3, Y: y_test_case3})
                print("Test error", test_val, "\n" "Test Prediction" "\n", test_hy )
                print("---------------------------")
                print("Case3_Crack_test start")
                print("---------------------------")
                test_val, test_hy = sess.run([cost,hypothesis], feed_dict={X:x_test2_case3, Y: y_test2_case3})
                print("Test error", test_val, "\n" "Test Prediction" "\n", test_hy )
                print("---------------------------")
                print("Case3_Eclpise_test start")
                print("---------------------------")
                test_val, test_hy = sess.run([cost,hypothesis], feed_dict={X:x_test3_case3, Y: y_test3_case3})
                print("Test error", test_val, "\n" "Test Prediction" "\n", test_hy )
             
